# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://nitram_bot.github.io/lecture_base/"

git_url = "https://github.com/nitram_bot/lecture_base/tree/master/"

def custom_doc_links(name): return None
